### ISSUE TITLE
injection doesn't seem to be working

### ISSUE THREAD

**Issue by duanefields** [t3chnoboy/angular-hipster-seed#2]
Hey, thanks for putting this together.

For me, css and JS injection doesn't seem to be working, for either development or production targets.

**Comment by duanefields** [comment]
aha, my editor has "trim trailing whitespace" enabled and if you don't have whitespace at the end of your comments, it doesn't match the expected pattern, i.e. you get

```
<-- inject:js-->
```

rather than

```
<-- inject:js -->
```

Not sure why Jade does that....

**Comment by t3chnoboy** [comment]
I had the same issue when using injection with jade for the first time :smile:
It's great that you've figured it out by yourself :+1:  
Should have mentioned that in Readme.
